Repository nbQA-dev/nbQA, pull requests merged in 2020-10, with the labels that each got.

#288 Politely ask users to report bugs
  nbqa/__main__.py
  tests/conftest.py
  tests/remove_comments.py
  tests/test_runtime_errors.py
Labels: error reporting

#322 Github action: adding caching action to the tox.yml github action
  .github/workflows/autoupdate-pre-commit-config.yml
  .github/workflows/pre-commit.yml
  .github/workflows/tox.yml
Labels: CI/CD, enhancement, performance

#337 tox: removing redundant install deps in GH action
  .github/workflows/tox.yml
Labels: refactor

#347 Fix nbqa-doctest hook
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
Labels: bug, pre-commit

#348 Make some types explicit
  tests/tools/test_black.py
  tests/tools/test_isort_works.py
  tests/tools/test_pyupgrade.py
Labels: clean

#396 Add tests for docs
  .github/workflows/docs.yml
  docs/_templates/autosummary/attribute.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/method.rst
  docs/_templates/autosummary/module.rst
  docs/clean_build_artifacts.py
  docs/conf.py
  docs/modules.rst
  setup.py
  tox.ini
Labels: bug, documentation

#402 use multiline regex
  nbqa/__main__.py
Labels: clean
